name: Cypress e2e test

on:
  push:
    branches:
      - develop

jobs:
  e2e:
    name: Build 🚀 & Deploy 📩
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Cypress cli
        run: pnpm install -g cypress

      - name: Install Cypress
        run: cypress install

      - name: Run Cypress Chrome
        uses: cypress-io/github-action@v5
        with:
          browser: chrome

      - name: Run Firefox
        uses: cypress-io/github-action@v5
        with:
          browser: firefox

      - name: Run Edge
        uses: cypress-io/github-action@v5
        with:
          browser: edge
