name: Cypress run

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  e2e:
    name: Run Cypress e2e tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Cypress tests
        run: pnpm run test:e2e:prod
